name: JFrog Security Scans
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-run-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        id: setup-jfrog-cli
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: github-oidc-integration
          oidc-audience: jfrog-github
        env:
          JF_URL: ${{ vars.JF_URL }}

      - name: Build Application Binary
        id: build-npm
        run: |
          npm install grunt-cli
          npm install
          npm run build:server
          npm run package:ci

      - name: Docker Build
        id: docker-build
        run: |
          docker build -t juice-shop:${{ github.run_number }} .

      - name: JF Audit
        id: audit
        run: |
          set +e
          jf audit

      - name: JF Scan
        id: scan
        run: |
          set +e
          jf scan dist/* --licenses --vuln



      - name: JF Docker Scan
        id: docker-scan
        run: |
          set +e
          jf docker scan juice-shop:${{ github.run_number }} --licenses --vuln